//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppsLog
    {
        public System.Guid ID { get; set; }
        public string Name { get; set; }
        public System.DateTime Time { get; set; }
        public short Type { get; set; }
    }
}
