//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlockApp
    {
        public string ID { get; set; }
        public string AppName { get; set; }
        public string AppID { get; set; }
        public string Act { get; set; }
        public string Category { get; set; }
    }
}
