//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI
{
    using System;
    using System.Collections.Generic;
    
    public partial class InstalledApp
    {
        public string AppID { get; set; }
        public string DisplayName { get; set; }
        public string DisplayVersion { get; set; }
        public string InstallDate { get; set; }
        public string Publisher { get; set; }
        public string Path { get; set; }
        public string ChildID { get; set; }
        public System.DateTime ReciveDate { get; set; }
        public string DisplayIcon { get; set; }
    }
}
