//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI
{
    using System;
    using System.Collections.Generic;
    
    public partial class InternetUsage
    {
        public string ID { get; set; }
        public string InterfaceName { get; set; }
        public string ConnectionType { get; set; }
        public string DeviceName { get; set; }
        public double Usage { get; set; }
        public int Seconds { get; set; }
        public int Minutes { get; set; }
        public int Hour { get; set; }
    }
}
