//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Network
    {
        public string ChildID { get; set; }
        public string DivaceName { get; set; }
        public string ConnectionInterface { get; set; }
        public string ModemName { get; set; }
        public string IPv6 { get; set; }
        public string IPv4 { get; set; }
        public string Status { get; set; }
        public string ID { get; set; }
    }
}
