//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ParentDBEntities4 : DbContext
    {
        public ParentDBEntities4()
            : base("name=ParentDBEntities4")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AppsLimit> AppsLimits { get; set; }
        public virtual DbSet<AppsLog> AppsLogs { get; set; }
        public virtual DbSet<AppUsage> AppUsages { get; set; }
        public virtual DbSet<BlockApp> BlockApps { get; set; }
        public virtual DbSet<BlockUrl> BlockUrls { get; set; }
        public virtual DbSet<Datum> Data { get; set; }
        public virtual DbSet<HistoryURL> HistoryURLs { get; set; }
        public virtual DbSet<InternetUsage> InternetUsages { get; set; }
        public virtual DbSet<NetworkLimit> NetworkLimits { get; set; }
        public virtual DbSet<Process> Processes { get; set; }
        public virtual DbSet<ScreenShot> ScreenShots { get; set; }
        public virtual DbSet<SystemLimit> SystemLimits { get; set; }
        public virtual DbSet<SystemLog> SystemLogs { get; set; }
        public virtual DbSet<SystemUsage> SystemUsages { get; set; }
        public virtual DbSet<URLCategury> URLCateguries { get; set; }
        public virtual DbSet<AppCategory> AppCategories { get; set; }
        public virtual DbSet<InstalledApp> InstalledApps { get; set; }
        public virtual DbSet<Location> Locations { get; set; }
        public virtual DbSet<Network> Networks { get; set; }
        public virtual DbSet<NetworkAdaptor> NetworkAdaptors { get; set; }
        public virtual DbSet<RunningApp> RunningApps { get; set; }
        public virtual DbSet<UninstallOrInstall> UninstallOrInstalls { get; set; }
        public virtual DbSet<VPN> VPNs { get; set; }
    }
}
