//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Process
    {
        public string ID { get; set; }
        public string ProcessName { get; set; }
        public string ProcessId { get; set; }
        public string ExecutablePath { get; set; }
        public string StartTime { get; set; }
        public string EndTime { get; set; }
        public string OSName { get; set; }
    }
}
